[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[mounts]]
source = "dreams-seo-data"
destination = "/app/prisma/data"
