# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e62a98dc2628ff730e9ec7accf26fe2d"
name = "Dreams SEO"
application_url = "https://seo.dreamsnutrition.com.br"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products,read_content,write_content,read_themes,write_themes,read_online_store_pages,write_online_store_pages,read_online_store_navigation,read_files,write_files,read_locales,read_markets,read_orders,read_script_tags,write_script_tags,read_translations,write_translations,read_metaobjects,write_metaobjects,read_customer_events,write_pixels"

[auth]
redirect_urls = [ "https://seo.dreamsnutrition.com.br/auth/callback" ]

[pos]
embedded = false
